name: mathematics
description: A new Flutter application.

publish_to: 'none' 

version: 1.2.8+1
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.4
  http: ^1.3.0
  intl: ^0.19.0
  file_picker: ^8.0.2
  path_provider: ^2.0.10
  syncfusion_flutter_pdfviewer: ^24.1.45
  printing: ^5.9.1
  syncfusion_flutter_core: ^24.1.45
  circular_countdown_timer: ^0.2.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  universal_html: ^2.0.8
  font_awesome_flutter: ^10.8.0
  archive: ^3.5.0  # Actualizado a la última versión disponible


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/